/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klockimans;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author pfigat
 */
public class GUI extends javax.swing.JFrame {
    
    
  public static ArrayList <Klocek> globaltabKlocki = new ArrayList<>();
  private DatabaseManager dbManager;
  private AlgorithmResult lastResult;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        initializeDatabase();
    }
    
    private void initializeDatabase() {
        try {
            dbManager = new DatabaseManager();
            dbManager.createTableIfNotExists();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Błąd połączenia z bazą danych: " + e.getMessage(),
                "Błąd bazy danych", 
                JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new MyPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButton1.setText("Generowanie");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Układanie");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Zapis");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Odczyt");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );

        jSplitPane2.setTopComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel4);

        jPanel1.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean clearBefore = true;
        
        // Jeśli są już klocki, zapytaj co zrobić
        if (!globaltabKlocki.isEmpty()) {
            String[] options = {"Nowe klocki", "Dodaj do istniejących", "Wyczyść wszystko"};
            String choice = (String) JOptionPane.showInputDialog(
                this,
                "Masz już " + globaltabKlocki.size() + " klocków. Co chcesz zrobić?",
                "Generowanie klocków",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
            );
            
            if (choice == null) return;
            
            if (choice.equals(options[2])) {
                globaltabKlocki.clear();
                jPanel2.repaint();
                return;
            }
            
            clearBefore = choice.equals(options[0]);
        }
        
        // Zapytaj o liczbę klocków
        String countStr = JOptionPane.showInputDialog(
            this,
            "Podaj liczbę klocków do wygenerowania (1-100):",
            "Liczba klocków",
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (countStr == null || countStr.trim().isEmpty()) return;
        
        int count;
        try {
            count = Integer.parseInt(countStr.trim());
            if (count < 1 || count > 100) {
                JOptionPane.showMessageDialog(this,
                    "Liczba klocków musi być z zakresu 1-100!",
                    "Błąd",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Podaj poprawną liczbę całkowitą!",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (clearBefore) {
            globaltabKlocki.clear();
        }
        
        // Generuj klocki
        for (int i = 0; i < count; i++) {
            Klocek k = new Klocek(
                (int)(Math.random() * 100 + 100), 
                (int)(Math.random() * 100 + 100)
            );
            globaltabKlocki.add(k);
        }
        
        JOptionPane.showMessageDialog(this,
            "Wygenerowano " + count + " klocków.\nŁącznie: " + globaltabKlocki.size(),
            "Sukces",
            JOptionPane.INFORMATION_MESSAGE);
        
        jPanel2.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (globaltabKlocki.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Najpierw wygeneruj klocki!",
                "Brak klocków",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Wyświetl dialog wyboru algorytmu
        String[] algorithms = {
            "Algorytm podstawowy",
            "Brute Force (max 10 elementów)",
            "Zachłanny z obracaniem",
            "Zachłanny - sortowanie po powierzchni",
            "Zachłanny - sortowanie po wysokości", 
            "Zachłanny - sortowanie po szerokości",
            "Best-Fit",
            "📊 PORÓWNAJ WSZYSTKIE ALGORYTMY"
        };
        
        String choice = (String) JOptionPane.showInputDialog(
            this,
            "Wybierz algorytm układania:\n(Liczba klocków: " + globaltabKlocki.size() + ")",
            "Wybór algorytmu",
            JOptionPane.QUESTION_MESSAGE,
            null,
            algorithms,
            algorithms[0]
        );
        
        if (choice == null) return;
        
        if (choice.contains("PORÓWNAJ")) {
            compareAllAlgorithms();
            return;
        }
        
        Tafla tafla = new Tafla(jPanel2.getWidth(), jPanel2.getHeight());
        
        try {
            if (choice.equals(algorithms[0])) {
                // Algorytm podstawowy z kontrolą granic
                long startTime = System.nanoTime();
                ArrayList<Klocek> arranged = new ArrayList<>();
                ArrayList<Klocek> copies = new ArrayList<>();
                for (Klocek k : globaltabKlocki) {
                    copies.add(k.copy());
                }
                int skipped = Algorytmy.podstawowyWithBounds(tafla, copies, arranged);
                long executionTime = System.nanoTime() - startTime;
                
                lastResult = new AlgorithmResult("Algorytm podstawowy");
                lastResult.setBlocks(arranged);
                lastResult.setSkippedBlocks(skipped);
                lastResult.setWasteArea(Algorytmy.calculateWaste(arranged));
                lastResult.setExecutionTimeNano(executionTime);
                globaltabKlocki = arranged;
            } else if (choice.equals(algorithms[1])) {
                // Brute Force
                if (globaltabKlocki.size() > 10) {
                    JOptionPane.showMessageDialog(this, 
                        "Brute Force działa tylko dla max 10 elementów!\nMasz: " + globaltabKlocki.size(),
                        "Zbyt dużo elementów",
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
                lastResult = Algorytmy.bruteForcePacking(tafla, globaltabKlocki);
                globaltabKlocki = lastResult.getBlocks();
            } else if (choice.equals(algorithms[2])) {
                // Zachłanny z obracaniem
                lastResult = Algorytmy.greedyWithRotation(tafla, globaltabKlocki);
                globaltabKlocki = lastResult.getBlocks();
            } else if (choice.equals(algorithms[3])) {
                // Sortowanie po powierzchni
                lastResult = Algorytmy.greedySortedByArea(tafla, globaltabKlocki);
                globaltabKlocki = lastResult.getBlocks();
            } else if (choice.equals(algorithms[4])) {
                // Sortowanie po wysokości
                lastResult = Algorytmy.greedySortedByHeight(tafla, globaltabKlocki);
                globaltabKlocki = lastResult.getBlocks();
            } else if (choice.equals(algorithms[5])) {
                // Sortowanie po szerokości
                lastResult = Algorytmy.greedySortedByWidth(tafla, globaltabKlocki);
                globaltabKlocki = lastResult.getBlocks();
            } else if (choice.equals(algorithms[6])) {
                // Best-Fit
                lastResult = Algorytmy.bestFitPacking(tafla, globaltabKlocki);
                globaltabKlocki = lastResult.getBlocks();
            }
            
            // Oblicz dodatkowe statystyki
            if (lastResult != null) {
                calculateStatistics(lastResult, jPanel2.getWidth(), jPanel2.getHeight());
                displayResults(lastResult);
            }
            
            jPanel2.repaint();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Błąd podczas układania: " + e.getMessage(),
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Błąd układania klocków", e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void compareAllAlgorithms() {
        int boardWidth = jPanel2.getWidth();
        int boardHeight = jPanel2.getHeight();
        Tafla tafla = new Tafla(boardWidth, boardHeight);
        ArrayList<AlgorithmResult> results = new ArrayList<>();
        
        // Zapisz oryginalne klocki
        ArrayList<Klocek> originalBlocks = new ArrayList<>();
        for (Klocek k : globaltabKlocki) {
            originalBlocks.add(k.copy());
        }
        
        boolean includeBruteForce = globaltabKlocki.size() <= 10;
        
        // 1. Algorytm podstawowy
        try {
            ArrayList<Klocek> copies = copyBlocks(originalBlocks);
            ArrayList<Klocek> arranged = new ArrayList<>();
            long start = System.nanoTime();
            int skipped = Algorytmy.podstawowyWithBounds(tafla, copies, arranged);
            long time = System.nanoTime() - start;
            
            AlgorithmResult r = new AlgorithmResult("Podstawowy");
            r.setBlocks(arranged);
            r.setSkippedBlocks(skipped);
            r.setExecutionTimeNano(time);
            calculateStatistics(r, boardWidth, boardHeight);
            results.add(r);
        } catch (Exception e) { /* skip */ }
        
        // 2. Brute Force (tylko dla <= 10 klocków)
        if (includeBruteForce) {
            try {
                ArrayList<Klocek> copies = copyBlocks(originalBlocks);
                AlgorithmResult r = Algorytmy.bruteForcePacking(tafla, copies);
                r.setAlgorithmName("Brute Force");
                calculateStatistics(r, boardWidth, boardHeight);
                results.add(r);
            } catch (Exception e) { /* skip */ }
        }
        
        // 3. Zachłanny z obracaniem
        try {
            ArrayList<Klocek> copies = copyBlocks(originalBlocks);
            AlgorithmResult r = Algorytmy.greedyWithRotation(tafla, copies);
            calculateStatistics(r, boardWidth, boardHeight);
            results.add(r);
        } catch (Exception e) { /* skip */ }
        
        // 4. Sortowanie po powierzchni
        try {
            ArrayList<Klocek> copies = copyBlocks(originalBlocks);
            AlgorithmResult r = Algorytmy.greedySortedByArea(tafla, copies);
            calculateStatistics(r, boardWidth, boardHeight);
            results.add(r);
        } catch (Exception e) { /* skip */ }
        
        // 5. Sortowanie po wysokości
        try {
            ArrayList<Klocek> copies = copyBlocks(originalBlocks);
            AlgorithmResult r = Algorytmy.greedySortedByHeight(tafla, copies);
            calculateStatistics(r, boardWidth, boardHeight);
            results.add(r);
        } catch (Exception e) { /* skip */ }
        
        // 6. Sortowanie po szerokości
        try {
            ArrayList<Klocek> copies = copyBlocks(originalBlocks);
            AlgorithmResult r = Algorytmy.greedySortedByWidth(tafla, copies);
            calculateStatistics(r, boardWidth, boardHeight);
            results.add(r);
        } catch (Exception e) { /* skip */ }
        
        // 7. Best-Fit
        try {
            ArrayList<Klocek> copies = copyBlocks(originalBlocks);
            AlgorithmResult r = Algorytmy.bestFitPacking(tafla, copies);
            calculateStatistics(r, boardWidth, boardHeight);
            results.add(r);
        } catch (Exception e) { /* skip */ }
        
        // Sortuj po efektywności (najlepsza pierwsza), przy remisie po czasie (krótszy lepszy)
        results.sort((a, b) -> {
            int effCompare = Double.compare(b.getEfficiency(), a.getEfficiency());
            if (effCompare != 0) {
                return effCompare;
            }
            // Przy tej samej efektywności - krótszy czas wygrywa
            return Double.compare(a.getExecutionTimeMicros(), b.getExecutionTimeMicros());
        });
        
        // Wyświetl porównanie
        displayComparisonResults(results, originalBlocks.size(), includeBruteForce);
        
        // Ustaw klocki wg zwycięskiego algorytmu
        if (!results.isEmpty()) {
            AlgorithmResult best = results.get(0);
            globaltabKlocki.clear();
            globaltabKlocki.addAll(best.getBlocks());
            jPanel2.repaint();
        }
    }
    
    private ArrayList<Klocek> copyBlocks(ArrayList<Klocek> source) {
        ArrayList<Klocek> copies = new ArrayList<>();
        for (Klocek k : source) {
            copies.add(k.copy());
        }
        return copies;
    }
    
    private void displayComparisonResults(ArrayList<AlgorithmResult> results, int blockCount, boolean includedBruteForce) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("PORÓWNANIE ALGORYTMÓW (klocków: %d)%n", blockCount));
        sb.append("═".repeat(60)).append("\n\n");
        
        sb.append(String.format("%-22s %10s %10s %12s%n", "ALGORYTM", "EFEKT. %", "ODPAD", "CZAS"));
        sb.append("─".repeat(60)).append("\n");
        
        AlgorithmResult best = results.isEmpty() ? null : results.get(0);
        
        for (int i = 0; i < results.size(); i++) {
            AlgorithmResult r = results.get(i);
            String medal = switch(i) {
                case 0 -> "🥇 ";
                case 1 -> "🥈 ";
                case 2 -> "🥉 ";
                default -> "   ";
            };
            
            // Skróć długie nazwy do wyświetlenia w tabeli
            String shortName = shortenAlgorithmName(r.getAlgorithmName());
            
            sb.append(String.format("%s%-19s %9.2f%% %10.0f %12s%n",
                medal,
                shortName,
                r.getEfficiency(),
                r.getWasteArea(),
                r.getFormattedTime()
            ));
        }
        
        sb.append("─".repeat(60)).append("\n");
        
        if (!includedBruteForce) {
            sb.append("\n⚠️ Brute Force pominięty (>10 klocków)\n");
        }
        
        if (best != null) {
            sb.append(String.format("%n🏆 NAJLEPSZY: %s (%.2f%%)%n",
                best.getAlgorithmName(), best.getEfficiency()));
        }
        
        sb.append("\nCzy zapisać wszystkie wyniki do bazy danych?");
        
        JTextArea textArea = new JTextArea(sb.toString());
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(550, 350));
        
        int option = JOptionPane.showConfirmDialog(
            this, 
            scrollPane,
            "Porównanie algorytmów",
            JOptionPane.YES_NO_OPTION
        );
        
        if (option == JOptionPane.YES_OPTION && dbManager != null) {
            int saved = 0;
            for (AlgorithmResult r : results) {
                try {
                    dbManager.saveResult(r);
                    saved++;
                } catch (SQLException e) { /* skip */ }
            }
            JOptionPane.showMessageDialog(this,
                "Zapisano " + saved + " wyników do bazy danych.",
                "Sukces",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private String shortenAlgorithmName(String name) {
        return switch(name) {
            case "Zachłanny z obracaniem" -> "Zachłanny + rotacja";
            case "Zachłanny - sortowanie po powierzchni" -> "Sort. powierzchnia";
            case "Zachłanny - sortowanie po wysokości" -> "Sort. wysokość";
            case "Zachłanny - sortowanie po szerokości" -> "Sort. szerokość";
            default -> name;
        };
    }
    
    private void calculateStatistics(AlgorithmResult result, int boardWidth, int boardHeight) {
        double usedArea = 0;
        int fittedBlocks = 0;
        int outsideBlocks = 0;
        
        for (Klocek k : result.getBlocks()) {
            // Sprawdź czy klocek mieści się w granicach tafli
            int kRight = k.getPosx() + k.getWidth();
            int kBottom = k.getPosy() + k.getHeight();
            
            if (k.getPosx() >= 0 && k.getPosy() >= 0 && 
                kRight <= boardWidth && kBottom <= boardHeight) {
                // Klocek w pełni mieści się w tafli
                usedArea += k.getWidth() * k.getHeight();
                fittedBlocks++;
            } else {
                // Klocek wychodzi poza taflę - licz tylko część wewnątrz
                int visibleX = Math.max(0, Math.min(kRight, boardWidth) - Math.max(0, k.getPosx()));
                int visibleY = Math.max(0, Math.min(kBottom, boardHeight) - Math.max(0, k.getPosy()));
                usedArea += visibleX * visibleY;
                outsideBlocks++;
            }
        }
        
        // Stały rozmiar tafli jako total_area
        double totalArea = (double) boardWidth * boardHeight;
        double efficiency = (usedArea / totalArea) * 100.0;
        
        // Odpad = powierzchnia tafli - powierzchnia faktycznie pokryta przez klocki
        double wasteArea = totalArea - usedArea;
        
        result.setUsedArea(usedArea);
        result.setTotalArea(totalArea);
        result.setWasteArea(wasteArea);
        result.setEfficiency(efficiency);
        // Aktualizuj skippedBlocks: dotychczasowe + te które wyszły poza taflę
        result.setSkippedBlocks(result.getSkippedBlocks() + outsideBlocks);
        // Ustaw liczbę bloków tylko na te które w pełni się zmieściły
        result.setBlockCount(fittedBlocks);
    }
    
    private void displayResults(AlgorithmResult result) {
        String skippedInfo = "";
        if (result.getSkippedBlocks() > 0) {
            skippedInfo = String.format("\nNieumieszczone klocki: %d", result.getSkippedBlocks());
        }
        
        String message = String.format("""
            === WYNIKI ===
            
            Algorytm: %s
            Czas wykonania: %s
            Liczba klocków: %d%s
            
            Powierzchnia użyta: %.0f
            Powierzchnia całkowita: %.0f
            Odpad: %.2f
            Efektywność: %.2f%%
            
            Czy zapisać do bazy danych?""",
            result.getAlgorithmName(),
            result.getFormattedTime(),
            result.getBlocks().size(),
            skippedInfo,
            result.getUsedArea(),
            result.getTotalArea(),
            result.getWasteArea(),
            result.getEfficiency()
        );
        
        int option = JOptionPane.showConfirmDialog(
            this, 
            message,
            "Wyniki algorytmu",
            JOptionPane.YES_NO_OPTION
        );
        
        if (option == JOptionPane.YES_OPTION) {
            saveResultToDatabase(result);
        }
    }
    
    private void saveResultToDatabase(AlgorithmResult result) {
        if (dbManager == null) {
            JOptionPane.showMessageDialog(this,
                "Brak połączenia z bazą danych!",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            dbManager.saveResult(result);
            JOptionPane.showMessageDialog(this,
                "Wyniki zapisane do bazy danych!",
                "Sukces",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Błąd zapisu do bazy: " + e.getMessage(),
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String[] options = {
            "Zapisz klocki do pliku",
            "Pokaż ostatnie wyniki z BD",
            "Pokaż statystyki algorytmów"
        };
        
        String choice = (String) JOptionPane.showInputDialog(
            this,
            "Wybierz opcję:",
            "Opcje zapisu/odczytu",
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[0]
        );
        
        if (choice == null) return;
        
        if (choice.equals(options[0])) {
            // Zapis do pliku
            try (FileOutputStream p1 = new FileOutputStream("dane.txt");
                 ObjectOutputStream s = new ObjectOutputStream(p1)) {
                s.writeObject(globaltabKlocki);
                JOptionPane.showMessageDialog(this, "Klocki zapisane do pliku dane.txt");
            } catch (IOException ex) {
                logger.log(java.util.logging.Level.SEVERE, "Błąd zapisu do pliku", ex);
                JOptionPane.showMessageDialog(this, 
                    "Błąd zapisu do pliku: " + ex.getMessage(),
                    "Błąd",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else if (choice.equals(options[1])) {
            // Ostatnie wyniki z BD
            showDatabaseResults();
        } else if (choice.equals(options[2])) {
            // Statystyki
            showAlgorithmStatistics();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void showDatabaseResults() {
        if (dbManager == null) {
            JOptionPane.showMessageDialog(this,
                "Brak połączenia z bazą danych!",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String results = dbManager.getLastResults(10);
            JTextArea textArea = new JTextArea(results);
            textArea.setEditable(false);
            textArea.setRows(20);
            textArea.setColumns(50);
            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            
            JOptionPane.showMessageDialog(this,
                scrollPane,
                "Ostatnie 10 wyników",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Błąd odczytu z bazy: " + e.getMessage(),
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void showAlgorithmStatistics() {
        if (dbManager == null) {
            JOptionPane.showMessageDialog(this,
                "Brak połączenia z bazą danych!",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String stats = dbManager.getAlgorithmStatistics();
            JTextArea textArea = new JTextArea(stats);
            textArea.setEditable(false);
            textArea.setRows(20);
            textArea.setColumns(50);
            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            
            JOptionPane.showMessageDialog(this,
                scrollPane,
                "Statystyki algorytmów",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Błąd odczytu statystyk: " + e.getMessage(),
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    @SuppressWarnings("unchecked")
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try (FileInputStream p1 = new FileInputStream("dane.txt");
             ObjectInputStream s = new ObjectInputStream(p1)) {
            globaltabKlocki = (ArrayList<Klocek>) s.readObject();
            jPanel2.repaint();
            JOptionPane.showMessageDialog(this, 
                "Wczytano " + globaltabKlocki.size() + " klocków z pliku",
                "Sukces",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, 
                "Nie znaleziono pliku dane.txt",
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
        } catch (IOException | ClassNotFoundException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Błąd odczytu pliku", ex);
            JOptionPane.showMessageDialog(this, 
                "Błąd odczytu pliku: " + ex.getMessage(),
                "Błąd",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GUI gui = new GUI();
            gui.setVisible(true);
            
            // Dodaj WindowListener do zamykania połączenia z BD
            gui.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    if (gui.dbManager != null) {
                        gui.dbManager.close();
                    }
                }
            });
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
