/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package klockimans;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author pfigat
 */
public class MyPanel extends javax.swing.JPanel {

    // Paleta kolorów dla klocków
    private static final Color[] BLOCK_COLORS = {
        new Color(76, 175, 80),    // Zielony
        new Color(33, 150, 243),   // Niebieski
        new Color(156, 39, 176),   // Fioletowy
        new Color(255, 152, 0),    // Pomarańczowy
        new Color(0, 188, 212),    // Cyjan
        new Color(233, 30, 99),    // Różowy
        new Color(139, 195, 74),   // Jasny zielony
        new Color(103, 58, 183),   // Ciemny fiolet
        new Color(255, 87, 34),    // Głęboki pomarańcz
        new Color(0, 150, 136)     // Morski
    };

    /**
     * Creates new form MyPanel
     */
    public MyPanel() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        // Rysuj granicę tafli (czerwona ramka)
        g.setColor(Color.RED);
        g.drawRect(0, 0, getWidth() - 1, getHeight() - 1);
        // Druga linia dla lepszej widoczności
        g.drawRect(1, 1, getWidth() - 3, getHeight() - 3);
   
        // Rysuj klocki z kolorami
        int colorIndex = 0;
        for (Klocek k : GUI.globaltabKlocki) {
            // Wybierz kolor dla klocka (cyklicznie z palety)
            Color blockColor = BLOCK_COLORS[colorIndex % BLOCK_COLORS.length];
            
            // Wypełnij klocek kolorem
            g.setColor(blockColor);
            g.fillRect(k.getPosx(), k.getPosy(), k.getWidth(), k.getHeight());
            
            // Narysuj obramowanie klocka (ciemniejszy odcień)
            g.setColor(blockColor.darker());
            g.drawRect(k.getPosx(), k.getPosy(), k.getWidth(), k.getHeight());
            
            colorIndex++;
        }
        
        // Wyświetl informacje o klockach i rozmiar tafli
        g.setColor(Color.BLACK);
        g.drawString("Liczba klocków: " + GUI.globaltabKlocki.size() + 
                     " | Tafla: " + getWidth() + "x" + getHeight(), 10, 20);
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
